export const meta = {
  slug: "cat-unicorn",
  title: "Cat Unicorn",
  description:
    "Music-driven WebGL hero featuring a 3D cat with animated EQ bars, scanlines, a live audio ticker, and a glass-shimmer headline. Autoplay background track with toggle control.",
  category: "unicorn-section",
  preview: "/previews/unicorn-sections/cat-unicorn/preview.mov",
  github: "GeorgeHastings",
  tags: [
    "unicorn",
    "webgl",
    "animated",
    "3d",
    "cat",
    "music",
    "audio",
    "dark",
    "hero",
    "scanlines",
    "ticker",
    "editorial",
  ],
  dependencies: ["unicornstudio-react", "framer-motion"],
  registryDependencies: [],
  version: 1,
  views: 0,
  likes: 0,
  installs: 0,
} as const
