export const meta = {
  slug: "paper-grid",
  title: "Paper Grid",
  description:
    "Three translucent certificates printed on glass, hanging side by side and bending like real paper. Drag a sheet to turn it, hover to light it — all three share one WebGL context. Inspired by ThreeUI's ThreeDPaper.",
  category: "grid-sections",
  preview: "/previews/grid-sections/paper-grid/preview.mov",
  github: "vij-sameerb5",
  tags: [
    "grid",
    "webgl",
    "three",
    "paper",
    "glass",
    "certificate",
    "shader",
    "drag",
    "3d",
    "dark",
    "interactive",
    "animated",
  ],
  dependencies: ["three"],
  registryDependencies: [],
  version: 1,
  views: 0,
  likes: 0,
  installs: 0,
} as const
