export const meta = {
  slug: "plane-unicorn",
  title: "Plane Unicorn",
  description:
    "3D interactive aircraft hero built with Unicorn Studio — cursor-tracked Airbus A380 against a deep space backdrop with red light trail, animated telemetry ticker, and SKYWINKS editorial branding.",
  category: "unicorn-section",
  preview: "/previews/unicorn-sections/plane-unicorn/preview.mov",
  github: "GeorgeHastings",
  tags: [
    "unicorn",
    "webgl",
    "animated",
    "3d",
    "plane",
    "aviation",
    "interactive",
    "cursor",
    "mouse",
    "dark",
    "hero",
    "ticker",
    "editorial",
    "space",
  ],
  dependencies: ["unicornstudio-react", "framer-motion"],
  registryDependencies: [],
  version: 1,
  views: 0,
  likes: 0,
  installs: 0,
} as const
