"use client"

import { useState, useSyncExternalStore } from "react"
import { Check, Copy } from "lucide-react"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"

export const PACKAGE_MANAGERS = ["npm", "pnpm", "yarn", "bun"] as const
export type PackageManager = (typeof PACKAGE_MANAGERS)[number]

const STORAGE_KEY = "zepa-package-manager"

/**
 * Converts an npm-based command (generated by the registry) into the
 * equivalent command for another package manager. Purely mechanical —
 * nothing is hardcoded per component, so anything produced by
 * `npm run build:registry` converts automatically.
 */
export function convertCommand(command: string, pm: PackageManager): string {
  if (pm === "npm") return command

  if (command.startsWith("npx ")) {
    const rest = command.slice("npx ".length)
    switch (pm) {
      case "pnpm":
        return `pnpm dlx ${rest}`
      case "yarn":
        return `yarn dlx ${rest}`
      case "bun":
        return `bunx --bun ${rest}`
    }
  }

  if (command.startsWith("npm install ")) {
    const rest = command.slice("npm install ".length)
    switch (pm) {
      case "pnpm":
        return `pnpm add ${rest}`
      case "yarn":
        return `yarn add ${rest}`
      case "bun":
        return `bun add ${rest}`
    }
  }

  return command
}

const PM_CHANGE_EVENT = "zepa-pm-change"

function subscribePm(onStoreChange: () => void) {
  window.addEventListener("storage", onStoreChange)
  window.addEventListener(PM_CHANGE_EVENT, onStoreChange)
  return () => {
    window.removeEventListener("storage", onStoreChange)
    window.removeEventListener(PM_CHANGE_EVENT, onStoreChange)
  }
}

function getPmSnapshot(): PackageManager {
  const saved = window.localStorage.getItem(STORAGE_KEY)
  if (saved && (PACKAGE_MANAGERS as readonly string[]).includes(saved)) {
    return saved as PackageManager
  }
  return "npm"
}

/** Reads the saved package manager choice (falls back to npm). */
export function usePackageManager() {
  const pm = useSyncExternalStore(subscribePm, getPmSnapshot, () => "npm" as PackageManager)

  function selectPm(next: PackageManager) {
    window.localStorage.setItem(STORAGE_KEY, next)
    window.dispatchEvent(new Event(PM_CHANGE_EVENT))
  }

  return [pm, selectPm] as const
}

function InstallCopyButton({
  value,
  label,
  onCopied,
}: {
  value: string
  label: string
  onCopied?: () => void
}) {
  const [copied, setCopied] = useState(false)

  async function handleCopy() {
    await navigator.clipboard.writeText(value)
    onCopied?.()
    setCopied(true)
    window.setTimeout(() => setCopied(false), 2000)
  }

  return (
    <Button
      type="button"
      variant="outline"
      size="sm"
      onClick={handleCopy}
      className="h-7 border-white/10 bg-white/5 px-2.5 text-xs text-white hover:bg-white/10 hover:text-white [&_svg]:size-3"
    >
      {copied ? (
        <Check className="size-3.5" />
      ) : (
        <Copy className="size-3.5" />
      )}
      {copied ? "Copied" : label}
    </Button>
  )
}

interface InstallCommandBlockProps {
  label: string
  command: string
  pm: PackageManager
  onPmChange: (pm: PackageManager) => void
  copyLabel: string
  onCopied?: () => void
}

export function InstallCommandBlock({
  label,
  command,
  pm,
  onPmChange,
  copyLabel,
  onCopied,
}: InstallCommandBlockProps) {
  const converted = convertCommand(command, pm)

  return (
    <div className="space-y-2">
      <div className="flex items-end justify-between gap-2">
        <p className="text-xs text-white/45">{label}</p>

        <div className="flex gap-0.5 rounded-lg border border-white/10 bg-white/5 p-0.5">
          {PACKAGE_MANAGERS.map((manager) => (
            <button
              key={manager}
              type="button"
              onClick={() => onPmChange(manager)}
              className={cn(
                "rounded-md px-2 py-1 font-mono text-[11px] leading-none transition",
                manager === pm
                  ? "bg-white font-medium text-black"
                  : "text-white/45 hover:bg-white/10 hover:text-white/80"
              )}
            >
              {manager}
            </button>
          ))}
        </div>
      </div>

      <pre className="scrollbar-hidden overflow-x-auto rounded-lg border border-white/10 bg-zinc-950 p-3 text-xs text-white/80">
        {converted}
      </pre>

      <InstallCopyButton value={converted} label={copyLabel} onCopied={onCopied} />
    </div>
  )
}
