export const meta = {
  slug: "dove-unicorn",
  title: "Dove Unicorn",
  description:
    "Gallery-white hover-reveal hero — a porcelain dove relief hides under a blank canvas until the cursor brushes it back into view. Museum-label typography, serif italic accents, and a hairline passe-partout frame.",
  category: "unicorn-section",
  preview: "/previews/unicorn-sections/dove-unicorn/preview.mov",
  github: "vij-sameerb5",
  tags: [
    "unicorn",
    "webgl",
    "animated",
    "hover",
    "reveal",
    "dove",
    "light",
    "white",
    "minimal",
    "editorial",
    "gallery",
    "hero",
  ],
  dependencies: ["unicornstudio-react", "framer-motion"],
  registryDependencies: [],
  version: 1,
  views: 0,
  likes: 0,
  installs: 0,
} as const
