"use client"

/**
 * GithubZepa — contribution calendar.
 *
 * A year of activity as a seven-row grid of levelled cells, with month labels,
 * a hover tooltip, a legend and a stats line.
 *
 *   <GithubZepa />
 *   <GithubZepa username="you" days={myDays} total={6403} />
 *   <GithubZepa cellSize={12} cellGap={3} cellShape="circle" />
 *
 * Implementation notes:
 *  - **No network calls.** CI greps `content/registry` for request APIs and
 *    fails the build on a match, so data arrives through the `days` prop
 *    instead. The default set is generated by a seeded PRNG at module scope —
 *    deterministic, so the server and the client render identically.
 *    (That grep matches comments too, not just code — mention a request API by
 *    name in a comment and the build fails on your documentation.)
 *  - **No `new Date()` during render.** `endDate` is a prop with a fixed
 *    default; deriving "today" at render time shifts every cell between server
 *    and client and mismatches hydration.
 *  - Colours are the GitHub ramp, unchanged. No `font-family`; typography
 *    inherits from the host app.
 *  - Every class is prefixed `gz-`.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import type { CSSProperties } from "react"

export type GithubZepaLevel = 0 | 1 | 2 | 3 | 4

export interface GithubZepaDay {
  /** ISO date, YYYY-MM-DD. */
  date: string
  level: GithubZepaLevel
  count?: number
}

export interface GithubZepaColors {
  level0: string
  level1: string
  level2: string
  level3: string
  level4: string
}

export interface GithubZepaProps {
  username?: string
  /** Contribution days. Defaults to a deterministic generated year. */
  days?: GithubZepaDay[]
  /** Headline number. Defaults to the sum of the day counts. */
  total?: number
  /** Last day of the grid, YYYY-MM-DD. Never derive this from `new Date()`. */
  endDate?: string
  /** Columns to draw. */
  weeks?: number
  cellSize?: number
  cellGap?: number
  cellShape?: "rounded" | "circle"
  colors?: GithubZepaColors
  showMonthLabels?: boolean
  showLegend?: boolean
  showStats?: boolean
  variant?: "tile" | "bare"
  className?: string
}

const GITHUB_COLORS: GithubZepaColors = {
  level0: "#0a0a0a",
  level1: "#0e4429",
  level2: "#006d32",
  level3: "#26a641",
  level4: "#39d353",
}

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
const MONTHS_LONG = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
]

function parseDate(value: string) {
  const [y, m, d] = value.split("-").map(Number)
  return new Date(y ?? 1970, (m ?? 1) - 1, d ?? 1)
}

function formatDate(date: Date) {
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, "0")
  const d = String(date.getDate()).padStart(2, "0")
  return `${y}-${m}-${d}`
}

function addDays(date: Date, days: number) {
  const next = new Date(date)
  next.setDate(next.getDate() + days)
  return next
}

function ordinal(day: number) {
  if (day > 3 && day < 21) return "th"
  if (day % 10 === 1) return "st"
  if (day % 10 === 2) return "nd"
  if (day % 10 === 3) return "rd"
  return "th"
}

/**
 * Seeded PRNG. The default dataset must be identical on the server and in the
 * browser, so `Math.random()` is not an option — it would repaint the whole
 * grid on hydration.
 */
function seeded(seed: number) {
  let state = seed
  return () => {
    state |= 0
    state = (state + 0x6d2b79f5) | 0
    let t = Math.imul(state ^ (state >>> 15), 1 | state)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const DEFAULT_END = "2026-08-11"

function generateYear(endDate: string, weeks: number): GithubZepaDay[] {
  const random = seeded(0x2e9a)
  const end = parseDate(endDate)
  const days: GithubZepaDay[] = []

  for (let offset = weeks * 7 - 1; offset >= 0; offset -= 1) {
    const date = addDays(end, -offset)
    const weekday = date.getDay()
    // Weekends run quieter, and activity ramps across the year.
    const season = 0.45 + (1 - offset / (weeks * 7)) * 0.5
    const rest = weekday === 0 || weekday === 6 ? 0.55 : 1
    const roll = random() * season * rest

    let level: GithubZepaLevel = 0
    if (roll > 0.62) level = 4
    else if (roll > 0.46) level = 3
    else if (roll > 0.3) level = 2
    else if (roll > 0.12) level = 1

    const count = level === 0 ? 0 : Math.round(level * 4 + random() * level * 5)
    days.push({ date: formatDate(date), level, count })
  }

  return days
}

const CSS = `
.gz-shell{display:flex;width:100%;justify-content:center}
.gz-shell *{box-sizing:border-box}
.gz-root{width:fit-content;max-width:100%;overflow:hidden;border:1px solid var(--gz-line);border-radius:6px;background:var(--gz-bg);color:var(--gz-fg)}
.gz-root[data-variant="bare"]{border:0;border-radius:0;background:transparent}
.gz-inner{display:flex;flex-direction:column;gap:12px;padding:12px}

.gz-scroll{position:relative;overflow-x:auto;scrollbar-width:none;-ms-overflow-style:none}
.gz-scroll::-webkit-scrollbar{display:none}
.gz-scroll svg{display:block;overflow:visible}

.gz-tip{position:absolute;z-index:50;padding:4px 10px;border:1px solid rgba(115,115,115,.3);border-radius:4px;background:var(--gz-tip);font-size:11px;font-weight:500;color:#fff;white-space:nowrap;pointer-events:none;box-shadow:0 4px 10px rgba(0,0,0,.5);transform:translate(-50%,calc(-100% - 6px))}
.gz-tip::after{content:"";position:absolute;left:50%;bottom:0;width:6px;height:6px;background:var(--gz-tip);border-right:1px solid rgba(115,115,115,.3);border-bottom:1px solid rgba(115,115,115,.3);transform:translate(-50%,50%) rotate(45deg)}

.gz-foot{display:flex;align-items:center;justify-content:space-between;gap:16px}
.gz-legend{display:flex;flex-wrap:wrap;align-items:center;gap:16px;flex-shrink:0;margin-top:2px;font-size:12px;color:var(--gz-muted)}
.gz-scale{display:flex;align-items:center;gap:6px}
.gz-scale svg{display:block}

.gz-stats{display:flex;flex:1;flex-wrap:wrap;justify-content:flex-end;margin-left:auto;font-size:14px;letter-spacing:.01em}
.gz-stats a{display:flex;align-items:center;gap:4px;color:#a3a3a3;text-decoration:none;-webkit-user-select:none;user-select:none}
.gz-name{font-weight:600;color:#e5e5e5}
.gz-count{font-weight:700;color:#39d353}
.gz-site{font-weight:600;color:#e5e5e5;text-decoration:underline;text-decoration-color:#a3a3a3;text-underline-offset:4px}
`

export function GithubZepa({
  username = "zepa-ui",
  days,
  total,
  endDate = DEFAULT_END,
  weeks = 53,
  cellSize = 15,
  cellGap = 4,
  cellShape = "rounded",
  colors = GITHUB_COLORS,
  showMonthLabels = true,
  showLegend = true,
  showStats = true,
  variant = "tile",
  className,
}: GithubZepaProps) {
  const [tip, setTip] = useState<{ x: number; y: number; text: string } | null>(
    null
  )
  const scrollRef = useRef<HTMLDivElement>(null)

  const dataset = useMemo(
    () => days ?? generateYear(endDate, weeks),
    [days, endDate, weeks]
  )

  const byDate = useMemo(() => {
    const map = new Map<string, GithubZepaDay>()
    for (const day of dataset) map.set(day.date, day)
    return map
  }, [dataset])

  const grid = useMemo(() => {
    const end = parseDate(endDate)
    // Walk back a whole number of weeks, then align to the preceding Sunday so
    // every column is a real calendar week.
    const rough = addDays(end, -(weeks * 7 - 1))
    const start = addDays(rough, -rough.getDay())

    const columns: (string | null)[][] = []
    const labels: Array<{ label: string; column: number }> = []
    let cursor = start
    let lastMonth = -1

    for (let column = 0; cursor <= end; column += 1) {
      const week: (string | null)[] = []
      for (let row = 0; row < 7; row += 1) {
        const inRange = cursor <= end
        week.push(inRange ? formatDate(cursor) : null)
        if (inRange && cursor.getMonth() !== lastMonth) {
          lastMonth = cursor.getMonth()
          labels.push({ label: MONTHS[cursor.getMonth()]!, column })
        }
        cursor = addDays(cursor, 1)
      }
      columns.push(week)
    }

    // Drop labels that would collide with the one before them.
    const spaced: Array<{ label: string; column: number }> = []
    labels.forEach((entry, index) => {
      const next = labels[index + 1]
      if (index === 0 && next && next.column - entry.column < 3) return
      const previous = spaced[spaced.length - 1]
      if (previous && entry.column - previous.column < 3) return
      spaced.push(entry)
    })

    return { columns, labels: spaced }
  }, [endDate, weeks])

  const grandTotal = useMemo(
    () => total ?? dataset.reduce((sum, day) => sum + (day.count ?? 0), 0),
    [total, dataset]
  )

  const step = cellSize + cellGap
  const labelHeight = showMonthLabels ? 20 : 0
  const svgWidth = grid.columns.length * step - cellGap
  const svgHeight = labelHeight + 7 * step - cellGap
  const radius = cellShape === "circle" ? cellSize / 2 : cellSize * 0.2

  const colorFor = useCallback(
    (level: GithubZepaLevel) =>
      colors[`level${level}` as keyof GithubZepaColors],
    [colors]
  )

  // Newest weeks are the interesting ones, so open scrolled to the end.
  useEffect(() => {
    const scroll = scrollRef.current
    if (scroll) scroll.scrollLeft = scroll.scrollWidth
  }, [dataset])

  const shellStyle = {
    "--gz-bg": "#0a0a0a",
    "--gz-fg": "#fafafa",
    "--gz-muted": "#a3a3a3",
    "--gz-line": "#262626",
    "--gz-tip": "#161b22",
  } as CSSProperties

  return (
    <div
      className={className ? `gz-shell ${className}` : "gz-shell"}
      style={shellStyle}
    >
      <style>{CSS}</style>

      <div className="gz-root" data-variant={variant}>
        <div className="gz-inner">
          <div className="gz-scroll" ref={scrollRef}>
            <svg
              width={svgWidth}
              height={svgHeight}
              viewBox={`0 0 ${svgWidth} ${svgHeight}`}
              role="img"
              aria-label={`${username} contribution calendar, ${grandTotal} contributions`}
            >
              {showMonthLabels
                ? grid.labels.map(({ label, column }) => (
                    <text
                      key={`${label}-${column}`}
                      x={column * step}
                      y={10}
                      fontSize={14}
                      fill="#fafafa"
                      fontFamily="inherit"
                    >
                      {label}
                    </text>
                  ))
                : null}

              {grid.columns.map((week, column) =>
                week.map((date, row) => {
                  if (!date) return null
                  const day = byDate.get(date)
                  const level = day?.level ?? 0

                  return (
                    <rect
                      key={date}
                      x={column * step}
                      y={labelHeight + row * step}
                      width={cellSize}
                      height={cellSize}
                      rx={radius}
                      fill={colorFor(level)}
                      onMouseEnter={() => {
                        const count = day?.count ?? 0
                        const parsed = parseDate(date)
                        const when = `${MONTHS_LONG[parsed.getMonth()]} ${parsed.getDate()}${ordinal(
                          parsed.getDate()
                        )}`
                        setTip({
                          x: column * step + cellSize / 2,
                          y: labelHeight + row * step,
                          text:
                            count === 0
                              ? `No contributions on ${when}.`
                              : `${count} contribution${count === 1 ? "" : "s"} on ${when}.`,
                        })
                      }}
                      onMouseLeave={() => setTip(null)}
                    />
                  )
                })
              )}
            </svg>

            {tip ? (
              <div className="gz-tip" style={{ left: tip.x, top: tip.y }}>
                {tip.text}
              </div>
            ) : null}
          </div>

          <div className="gz-foot">
            {showLegend ? (
              <div className="gz-legend">
                <div className="gz-scale">
                  <span>Less</span>
                  {([0, 1, 2, 3, 4] as GithubZepaLevel[]).map((level) => (
                    <svg key={level} width={cellSize} height={cellSize}>
                      <rect
                        width={cellSize}
                        height={cellSize}
                        rx={radius}
                        fill={colorFor(level)}
                      />
                    </svg>
                  ))}
                  <span>More</span>
                </div>
              </div>
            ) : null}

            {showStats ? (
              <div className="gz-stats">
                <a
                  href={`https://github.com/${username}`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <span className="gz-name">{username}</span>
                  <span>contributed</span>
                  <span className="gz-count">
                    {grandTotal.toLocaleString("en-US")}
                  </span>
                  <span>this year on</span>
                  <span className="gz-site">GitHub</span>
                </a>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  )
}

export default GithubZepa
