export const meta = {
  slug: "walking-unicorn",
  title: "Walking Unicorn",
  description:
    "Architectural WebGL hero shot from below a glass floor — silhouettes walk above you through frosted glass. POV perspective with editorial overlay and luxury elevation branding.",
  category: "unicorn-section",
  preview: "/previews/unicorn-sections/walking-unicorn/preview.mov",
  github: "GeorgeHastings",
  tags: [
    "unicorn",
    "webgl",
    "animated",
    "3d",
    "glass",
    "floor",
    "architecture",
    "pov",
    "dark",
    "hero",
    "light",
    "editorial",
  ],
  dependencies: ["unicornstudio-react", "framer-motion"],
  registryDependencies: [],
  version: 1,
  views: 0,
  likes: 0,
  installs: 0,
} as const
