export const meta = {
  slug: "earth-unicorn",
  title: "Earth Unicorn",
  description:
    "Surveillance-themed WebGL hero with a rotating 3D earth, global tracking aesthetic, and editorial typography.",
  category: "unicorn-section",
  preview: "/previews/unicorn-sections/earth-unicorn/preview.mov",
  github: "GeorgeHastings",
  tags: [
    "unicorn",
    "webgl",
    "animated",
    "3d",
    "earth",
    "globe",
    "tracking",
    "dark",
    "hero",
    "editorial",
    "surveillance",
    "motion",
  ],
  dependencies: ["unicornstudio-react", "framer-motion"],
  registryDependencies: [],
  version: 1,
  views: 0,
  likes: 0,
  installs: 0,
} as const
