export const meta = {
  slug: "figma-hero",
  title: "Figma Hero",
  description:
    "Inspired by the David Suárez portfolio — a hero staged as a live Figma canvas. Hovering any text reveals a real selection box with blue outline, corner handles, and a \"Text\" layer tag. A custom black arrow cursor labelled \"You\" replaces the pointer while a purple \"David\" collaborator cursor wanders the canvas on its own with organic wobble. The middle name renders as a glitchy bitmap, re-shuffling its pixel palette every 700ms on a canvas element. Includes a live NYC clock, vertical column guides, and staggered fade-up entrance on the four hero blocks.",
  category: "hero-sections",
  preview: "/previews/hero-sections/figma-hero/preview.mov",
  github: "vij-sameerb5",
  tags: [
    "hero",
    "figma",
    "canvas",
    "cursor",
    "collaborative",
    "portfolio",
    "glitch",
    "pixel",
    "interactive",
    "light",
    "animated",
    "landing",
  ],
  dependencies: [],
  registryDependencies: [],
  version: 1,
  views: 0,
  likes: 0,
  installs: 0,
} as const
