export const meta = {
  slug: "ring-unicorn",
  title: "Ring Unicorn",
  description:
    "Deep-space WebGL hero built with Unicorn Studio — glowing ring or portal structure with pulse animation and dark editorial overlay.",
  category: "unicorn-section",
  preview: "/previews/unicorn-sections/ring-unicorn/preview.mov",
  github: "GeorgeHastings",
  tags: [
    "unicorn",
    "webgl",
    "animated",
    "3d",
    "ring",
    "portal",
    "dark",
    "hero",
    "glow",
    "pulse",
    "space",
    "editorial",
  ],
  dependencies: ["unicornstudio-react", "framer-motion"],
  registryDependencies: [],
  version: 1,
  views: 0,
  likes: 0,
  installs: 0,
} as const
