// AUTO-GENERATED by scripts/build-registry.ts — do not edit manually.
// Run: npm run build:registry

import { meta as gridSectionsFeatured1Grid } from "./grid-sections/featured1-grid/meta"
import { meta as heroSectionsAirHero } from "./hero-sections/air-hero/meta"
import { meta as heroSectionsAmeroHero } from "./hero-sections/amero-hero/meta"
import { meta as heroSectionsAmindHero } from "./hero-sections/amind-hero/meta"
import { meta as heroSectionsBevelHero } from "./hero-sections/bevel-hero/meta"
import { meta as heroSectionsBluishHero } from "./hero-sections/bluish-hero/meta"
import { meta as heroSectionsBrutalHero } from "./hero-sections/brutal-hero/meta"
import { meta as heroSectionsCaledera } from "./hero-sections/caledera/meta"
import { meta as heroSectionsCardHero } from "./hero-sections/card-hero/meta"
import { meta as heroSectionsCrnacuraHero } from "./hero-sections/crnacura-hero/meta"
import { meta as heroSectionsDataanalyticsHero } from "./hero-sections/dataanalytics-hero/meta"
import { meta as heroSectionsDropsHero } from "./hero-sections/drops-hero/meta"
import { meta as heroSectionsFigmaHero } from "./hero-sections/figma-hero/meta"
import { meta as heroSectionsGleanHero } from "./hero-sections/glean-hero/meta"
import { meta as heroSectionsGlslHillsHero } from "./hero-sections/glsl-hills-hero/meta"
import { meta as heroSectionsLenaHero } from "./hero-sections/lena-hero/meta"
import { meta as heroSectionsMainframeHero } from "./hero-sections/mainframe-hero/meta"
import { meta as heroSectionsNewHero } from "./hero-sections/new-hero/meta"
import { meta as heroSectionsOsmosHero } from "./hero-sections/osmos-hero/meta"
import { meta as heroSectionsOyoHero } from "./hero-sections/oyo-hero/meta"
import { meta as heroSectionsPaperHero } from "./hero-sections/paper-hero/meta"
import { meta as heroSectionsPopHero } from "./hero-sections/pop-hero/meta"
import { meta as heroSectionsPosterscrollHero } from "./hero-sections/posterscroll-hero/meta"
import { meta as heroSectionsScroll1Hero } from "./hero-sections/scroll1-hero/meta"
import { meta as heroSectionsScrolldownHero } from "./hero-sections/scrolldown-hero/meta"
import { meta as heroSectionsSelfieHero } from "./hero-sections/selfie-hero/meta"
import { meta as heroSectionsSliderHero } from "./hero-sections/slider-hero/meta"
import { meta as heroSectionsSynthesiaHero } from "./hero-sections/synthesia-hero/meta"
import { meta as heroSectionsVaultHero } from "./hero-sections/vault-hero/meta"
import { meta as heroSectionsVercelHero } from "./hero-sections/vercel-hero/meta"
import { meta as heroSectionsVideo1Hero } from "./hero-sections/video1-hero/meta"
import { meta as heroSectionsWaveHero } from "./hero-sections/wave-hero/meta"
import { meta as heroSectionsZoomHero } from "./hero-sections/zoom-hero/meta"
import { meta as navbarSectionsClippedNavbar } from "./navbar-sections/clipped-navbar/meta"
import { meta as navbarSectionsCohortNavbar } from "./navbar-sections/cohort-navbar/meta"
import { meta as navbarSectionsCurvedNavbar } from "./navbar-sections/curved-navbar/meta"
import { meta as navbarSectionsPhotoNavbar } from "./navbar-sections/photo-navbar/meta"
import { meta as navbarSectionsSupasteNavbar } from "./navbar-sections/supaste-navbar/meta"
import { meta as navbarSectionsUpdatedNavbar } from "./navbar-sections/updated-navbar/meta"
import { meta as unicornSectionBlurUnicorn } from "./unicorn-section/blur-unicorn/meta"
import { meta as unicornSectionCatUnicorn } from "./unicorn-section/cat-unicorn/meta"
import { meta as unicornSectionCubeUnicorn } from "./unicorn-section/cube-unicorn/meta"
import { meta as unicornSectionDoveUnicorn } from "./unicorn-section/dove-unicorn/meta"
import { meta as unicornSectionEarthUnicorn } from "./unicorn-section/earth-unicorn/meta"
import { meta as unicornSectionGlassUnicorn } from "./unicorn-section/glass-unicorn/meta"
import { meta as unicornSectionHandUnicorn } from "./unicorn-section/hand-unicorn/meta"
import { meta as unicornSectionPlaneUnicorn } from "./unicorn-section/plane-unicorn/meta"
import { meta as unicornSectionRampUnicorn } from "./unicorn-section/ramp-unicorn/meta"
import { meta as unicornSectionRevealUnicorn } from "./unicorn-section/reveal-unicorn/meta"
import { meta as unicornSectionRigelUnicorn } from "./unicorn-section/rigel-unicorn/meta"
import { meta as unicornSectionRingUnicorn } from "./unicorn-section/ring-unicorn/meta"
import { meta as unicornSectionTreeUnicorn } from "./unicorn-section/tree-unicorn/meta"
import { meta as unicornSectionVoidUnicorn } from "./unicorn-section/void-unicorn/meta"
import { meta as unicornSectionWalkingUnicorn } from "./unicorn-section/walking-unicorn/meta"

export const registryItems = [
  gridSectionsFeatured1Grid,
  heroSectionsAirHero,
  heroSectionsAmeroHero,
  heroSectionsAmindHero,
  heroSectionsBevelHero,
  heroSectionsBluishHero,
  heroSectionsBrutalHero,
  heroSectionsCaledera,
  heroSectionsCardHero,
  heroSectionsCrnacuraHero,
  heroSectionsDataanalyticsHero,
  heroSectionsDropsHero,
  heroSectionsFigmaHero,
  heroSectionsGleanHero,
  heroSectionsGlslHillsHero,
  heroSectionsLenaHero,
  heroSectionsMainframeHero,
  heroSectionsNewHero,
  heroSectionsOsmosHero,
  heroSectionsOyoHero,
  heroSectionsPaperHero,
  heroSectionsPopHero,
  heroSectionsPosterscrollHero,
  heroSectionsScroll1Hero,
  heroSectionsScrolldownHero,
  heroSectionsSelfieHero,
  heroSectionsSliderHero,
  heroSectionsSynthesiaHero,
  heroSectionsVaultHero,
  heroSectionsVercelHero,
  heroSectionsVideo1Hero,
  heroSectionsWaveHero,
  heroSectionsZoomHero,
  navbarSectionsClippedNavbar,
  navbarSectionsCohortNavbar,
  navbarSectionsCurvedNavbar,
  navbarSectionsPhotoNavbar,
  navbarSectionsSupasteNavbar,
  navbarSectionsUpdatedNavbar,
  unicornSectionBlurUnicorn,
  unicornSectionCatUnicorn,
  unicornSectionCubeUnicorn,
  unicornSectionDoveUnicorn,
  unicornSectionEarthUnicorn,
  unicornSectionGlassUnicorn,
  unicornSectionHandUnicorn,
  unicornSectionPlaneUnicorn,
  unicornSectionRampUnicorn,
  unicornSectionRevealUnicorn,
  unicornSectionRigelUnicorn,
  unicornSectionRingUnicorn,
  unicornSectionTreeUnicorn,
  unicornSectionVoidUnicorn,
  unicornSectionWalkingUnicorn,
] as const

export type RegistryItem = (typeof registryItems)[number]
