// AUTO-GENERATED by scripts/build-registry.ts — do not edit manually.
// Run: npm run build:registry

import { meta as heroSectionsAmeroHero } from "./hero-sections/amero-hero/meta"
import { meta as heroSectionsAmindHero } from "./hero-sections/amind-hero/meta"
import { meta as heroSectionsBrutalHero } from "./hero-sections/brutal-hero/meta"
import { meta as heroSectionsCaledera } from "./hero-sections/caledera/meta"
import { meta as heroSectionsDataanalyticsHero } from "./hero-sections/dataanalytics-hero/meta"
import { meta as heroSectionsGleanHero } from "./hero-sections/glean-hero/meta"
import { meta as heroSectionsGlslHillsHero } from "./hero-sections/glsl-hills-hero/meta"
import { meta as heroSectionsMainframeHero } from "./hero-sections/mainframe-hero/meta"
import { meta as heroSectionsNewHero } from "./hero-sections/new-hero/meta"
import { meta as heroSectionsPosterscrollHero } from "./hero-sections/posterscroll-hero/meta"
import { meta as heroSectionsVaultHero } from "./hero-sections/vault-hero/meta"
import { meta as heroSectionsVercelHero } from "./hero-sections/vercel-hero/meta"

export const registryItems = [
  heroSectionsAmeroHero,
  heroSectionsAmindHero,
  heroSectionsBrutalHero,
  heroSectionsCaledera,
  heroSectionsDataanalyticsHero,
  heroSectionsGleanHero,
  heroSectionsGlslHillsHero,
  heroSectionsMainframeHero,
  heroSectionsNewHero,
  heroSectionsPosterscrollHero,
  heroSectionsVaultHero,
  heroSectionsVercelHero,
] as const

export type RegistryItem = (typeof registryItems)[number]
