// AUTO-GENERATED by scripts/build-registry.ts — do not edit manually.
// Run: npm run build:registry

import { meta as animationsCardsAnimation } from "./animations/cards-animation/meta"
import { meta as animationsScroll1Animation } from "./animations/scroll1-animation/meta"
import { meta as animationsScroll2Animation } from "./animations/scroll2-animation/meta"
import { meta as animationsScroll3Animation } from "./animations/scroll3-animation/meta"
import { meta as animationsScroll4Animation } from "./animations/scroll4-animation/meta"
import { meta as animationsScroll5Animation } from "./animations/scroll5-animation/meta"
import { meta as animationsScroll6Animation } from "./animations/scroll6-animation/meta"
import { meta as gridSectionsCompanionGrid } from "./grid-sections/companion-grid/meta"
import { meta as gridSectionsFeatured1Grid } from "./grid-sections/featured1-grid/meta"
import { meta as gridSectionsFeatured10Grid } from "./grid-sections/featured10-grid/meta"
import { meta as gridSectionsFeatured11Grid } from "./grid-sections/featured11-grid/meta"
import { meta as gridSectionsFeatured2Grid } from "./grid-sections/featured2-grid/meta"
import { meta as gridSectionsFeatured3Grid } from "./grid-sections/featured3-grid/meta"
import { meta as gridSectionsFeatured4Grid } from "./grid-sections/featured4-grid/meta"
import { meta as gridSectionsFeatured5Grid } from "./grid-sections/featured5-grid/meta"
import { meta as gridSectionsFeatured6Grid } from "./grid-sections/featured6-grid/meta"
import { meta as gridSectionsFeatured7Grid } from "./grid-sections/featured7-grid/meta"
import { meta as gridSectionsFeatured8Grid } from "./grid-sections/featured8-grid/meta"
import { meta as gridSectionsFeatured9Grid } from "./grid-sections/featured9-grid/meta"
import { meta as gridSectionsPaperGrid } from "./grid-sections/paper-grid/meta"
import { meta as heroSectionsAirHero } from "./hero-sections/air-hero/meta"
import { meta as heroSectionsAmeroHero } from "./hero-sections/amero-hero/meta"
import { meta as heroSectionsAmindHero } from "./hero-sections/amind-hero/meta"
import { meta as heroSectionsBevelHero } from "./hero-sections/bevel-hero/meta"
import { meta as heroSectionsBluishHero } from "./hero-sections/bluish-hero/meta"
import { meta as heroSectionsBrutalHero } from "./hero-sections/brutal-hero/meta"
import { meta as heroSectionsCaledera } from "./hero-sections/caledera/meta"
import { meta as heroSectionsCardHero } from "./hero-sections/card-hero/meta"
import { meta as heroSectionsCrnacuraHero } from "./hero-sections/crnacura-hero/meta"
import { meta as heroSectionsDataanalyticsHero } from "./hero-sections/dataanalytics-hero/meta"
import { meta as heroSectionsDropsHero } from "./hero-sections/drops-hero/meta"
import { meta as heroSectionsFigmaHero } from "./hero-sections/figma-hero/meta"
import { meta as heroSectionsGleanHero } from "./hero-sections/glean-hero/meta"
import { meta as heroSectionsGlslHillsHero } from "./hero-sections/glsl-hills-hero/meta"
import { meta as heroSectionsLenaHero } from "./hero-sections/lena-hero/meta"
import { meta as heroSectionsMainframeHero } from "./hero-sections/mainframe-hero/meta"
import { meta as heroSectionsNewHero } from "./hero-sections/new-hero/meta"
import { meta as heroSectionsOsmosHero } from "./hero-sections/osmos-hero/meta"
import { meta as heroSectionsOyoHero } from "./hero-sections/oyo-hero/meta"
import { meta as heroSectionsPaperHero } from "./hero-sections/paper-hero/meta"
import { meta as heroSectionsPopHero } from "./hero-sections/pop-hero/meta"
import { meta as heroSectionsPosterscrollHero } from "./hero-sections/posterscroll-hero/meta"
import { meta as heroSectionsScroll1Hero } from "./hero-sections/scroll1-hero/meta"
import { meta as heroSectionsScrolldownHero } from "./hero-sections/scrolldown-hero/meta"
import { meta as heroSectionsSelfieHero } from "./hero-sections/selfie-hero/meta"
import { meta as heroSectionsSliderHero } from "./hero-sections/slider-hero/meta"
import { meta as heroSectionsSynthesiaHero } from "./hero-sections/synthesia-hero/meta"
import { meta as heroSectionsVaultHero } from "./hero-sections/vault-hero/meta"
import { meta as heroSectionsVercelHero } from "./hero-sections/vercel-hero/meta"
import { meta as heroSectionsVideo1Hero } from "./hero-sections/video1-hero/meta"
import { meta as heroSectionsWaveHero } from "./hero-sections/wave-hero/meta"
import { meta as heroSectionsZavedaHero } from "./hero-sections/zaveda-hero/meta"
import { meta as heroSectionsZoomHero } from "./hero-sections/zoom-hero/meta"
import { meta as interactiveIllustrationsBeamZepa } from "./interactive-illustrations/beam-zepa/meta"
import { meta as interactiveIllustrationsCalendarZepa } from "./interactive-illustrations/calendar-zepa/meta"
import { meta as interactiveIllustrationsCardsZepa } from "./interactive-illustrations/cards-zepa/meta"
import { meta as interactiveIllustrationsGithubZepa } from "./interactive-illustrations/github-zepa/meta"
import { meta as interactiveIllustrationsHalfZepa } from "./interactive-illustrations/half-zepa/meta"
import { meta as interactiveIllustrationsNotificationZepa } from "./interactive-illustrations/notification-zepa/meta"
import { meta as interactiveIllustrationsNotifyZepa } from "./interactive-illustrations/notify-zepa/meta"
import { meta as interactiveIllustrationsReportZepa } from "./interactive-illustrations/report-zepa/meta"
import { meta as interactiveIllustrationsRingZepa } from "./interactive-illustrations/ring-zepa/meta"
import { meta as interactiveIllustrationsThreatZepa } from "./interactive-illustrations/threat-zepa/meta"
import { meta as interactiveIllustrationsTimelineZepa } from "./interactive-illustrations/timeline-zepa/meta"
import { meta as interactiveIllustrationsZepaDiagram } from "./interactive-illustrations/zepa-diagram/meta"
import { meta as interactiveIllustrationsZepaFolder } from "./interactive-illustrations/zepa-folder/meta"
import { meta as interactiveIllustrationsZoomZepa } from "./interactive-illustrations/zoom-zepa/meta"
import { meta as navbarSectionsClippedNavbar } from "./navbar-sections/clipped-navbar/meta"
import { meta as navbarSectionsCohortNavbar } from "./navbar-sections/cohort-navbar/meta"
import { meta as navbarSectionsCurvedNavbar } from "./navbar-sections/curved-navbar/meta"
import { meta as navbarSectionsPhotoNavbar } from "./navbar-sections/photo-navbar/meta"
import { meta as navbarSectionsSupasteNavbar } from "./navbar-sections/supaste-navbar/meta"
import { meta as navbarSectionsUpdatedNavbar } from "./navbar-sections/updated-navbar/meta"
import { meta as unicornSectionBlurUnicorn } from "./unicorn-section/blur-unicorn/meta"
import { meta as unicornSectionCatUnicorn } from "./unicorn-section/cat-unicorn/meta"
import { meta as unicornSectionCubeUnicorn } from "./unicorn-section/cube-unicorn/meta"
import { meta as unicornSectionDoveUnicorn } from "./unicorn-section/dove-unicorn/meta"
import { meta as unicornSectionEarthUnicorn } from "./unicorn-section/earth-unicorn/meta"
import { meta as unicornSectionGlassUnicorn } from "./unicorn-section/glass-unicorn/meta"
import { meta as unicornSectionHandUnicorn } from "./unicorn-section/hand-unicorn/meta"
import { meta as unicornSectionPlaneUnicorn } from "./unicorn-section/plane-unicorn/meta"
import { meta as unicornSectionRampUnicorn } from "./unicorn-section/ramp-unicorn/meta"
import { meta as unicornSectionRevealUnicorn } from "./unicorn-section/reveal-unicorn/meta"
import { meta as unicornSectionRigelUnicorn } from "./unicorn-section/rigel-unicorn/meta"
import { meta as unicornSectionRingUnicorn } from "./unicorn-section/ring-unicorn/meta"
import { meta as unicornSectionTreeUnicorn } from "./unicorn-section/tree-unicorn/meta"
import { meta as unicornSectionVoidUnicorn } from "./unicorn-section/void-unicorn/meta"
import { meta as unicornSectionWalkingUnicorn } from "./unicorn-section/walking-unicorn/meta"

export const registryItems = [
  animationsCardsAnimation,
  animationsScroll1Animation,
  animationsScroll2Animation,
  animationsScroll3Animation,
  animationsScroll4Animation,
  animationsScroll5Animation,
  animationsScroll6Animation,
  gridSectionsCompanionGrid,
  gridSectionsFeatured1Grid,
  gridSectionsFeatured10Grid,
  gridSectionsFeatured11Grid,
  gridSectionsFeatured2Grid,
  gridSectionsFeatured3Grid,
  gridSectionsFeatured4Grid,
  gridSectionsFeatured5Grid,
  gridSectionsFeatured6Grid,
  gridSectionsFeatured7Grid,
  gridSectionsFeatured8Grid,
  gridSectionsFeatured9Grid,
  gridSectionsPaperGrid,
  heroSectionsAirHero,
  heroSectionsAmeroHero,
  heroSectionsAmindHero,
  heroSectionsBevelHero,
  heroSectionsBluishHero,
  heroSectionsBrutalHero,
  heroSectionsCaledera,
  heroSectionsCardHero,
  heroSectionsCrnacuraHero,
  heroSectionsDataanalyticsHero,
  heroSectionsDropsHero,
  heroSectionsFigmaHero,
  heroSectionsGleanHero,
  heroSectionsGlslHillsHero,
  heroSectionsLenaHero,
  heroSectionsMainframeHero,
  heroSectionsNewHero,
  heroSectionsOsmosHero,
  heroSectionsOyoHero,
  heroSectionsPaperHero,
  heroSectionsPopHero,
  heroSectionsPosterscrollHero,
  heroSectionsScroll1Hero,
  heroSectionsScrolldownHero,
  heroSectionsSelfieHero,
  heroSectionsSliderHero,
  heroSectionsSynthesiaHero,
  heroSectionsVaultHero,
  heroSectionsVercelHero,
  heroSectionsVideo1Hero,
  heroSectionsWaveHero,
  heroSectionsZavedaHero,
  heroSectionsZoomHero,
  interactiveIllustrationsBeamZepa,
  interactiveIllustrationsCalendarZepa,
  interactiveIllustrationsCardsZepa,
  interactiveIllustrationsGithubZepa,
  interactiveIllustrationsHalfZepa,
  interactiveIllustrationsNotificationZepa,
  interactiveIllustrationsNotifyZepa,
  interactiveIllustrationsReportZepa,
  interactiveIllustrationsRingZepa,
  interactiveIllustrationsThreatZepa,
  interactiveIllustrationsTimelineZepa,
  interactiveIllustrationsZepaDiagram,
  interactiveIllustrationsZepaFolder,
  interactiveIllustrationsZoomZepa,
  navbarSectionsClippedNavbar,
  navbarSectionsCohortNavbar,
  navbarSectionsCurvedNavbar,
  navbarSectionsPhotoNavbar,
  navbarSectionsSupasteNavbar,
  navbarSectionsUpdatedNavbar,
  unicornSectionBlurUnicorn,
  unicornSectionCatUnicorn,
  unicornSectionCubeUnicorn,
  unicornSectionDoveUnicorn,
  unicornSectionEarthUnicorn,
  unicornSectionGlassUnicorn,
  unicornSectionHandUnicorn,
  unicornSectionPlaneUnicorn,
  unicornSectionRampUnicorn,
  unicornSectionRevealUnicorn,
  unicornSectionRigelUnicorn,
  unicornSectionRingUnicorn,
  unicornSectionTreeUnicorn,
  unicornSectionVoidUnicorn,
  unicornSectionWalkingUnicorn,
] as const

export type RegistryItem = (typeof registryItems)[number]
