// AUTO-GENERATED by scripts/build-registry.ts — do not edit manually.
// Run: npm run build:registry

import type { ComponentType } from "react"

type DemoModule = { default: ComponentType }

export const registryLoaders: Record<
  string,
  {
    demo: () => Promise<DemoModule>
  }
> = {
  "amero-hero": {
    demo: () => import("./hero-sections/amero-hero/demo"),
  },
  "amind-hero": {
    demo: () => import("./hero-sections/amind-hero/demo"),
  },
  "brutal-hero": {
    demo: () => import("./hero-sections/brutal-hero/demo"),
  },
  "caledera": {
    demo: () => import("./hero-sections/caledera/demo"),
  },
  "crnacura-hero": {
    demo: () => import("./hero-sections/crnacura-hero/demo"),
  },
  "dataanalytics-hero": {
    demo: () => import("./hero-sections/dataanalytics-hero/demo"),
  },
  "drops-hero": {
    demo: () => import("./hero-sections/drops-hero/demo"),
  },
  "glean-hero": {
    demo: () => import("./hero-sections/glean-hero/demo"),
  },
  "glsl-hills-hero": {
    demo: () => import("./hero-sections/glsl-hills-hero/demo"),
  },
  "mainframe-hero": {
    demo: () => import("./hero-sections/mainframe-hero/demo"),
  },
  "new-hero": {
    demo: () => import("./hero-sections/new-hero/demo"),
  },
  "posterscroll-hero": {
    demo: () => import("./hero-sections/posterscroll-hero/demo"),
  },
  "slider-hero": {
    demo: () => import("./hero-sections/slider-hero/demo"),
  },
  "vault-hero": {
    demo: () => import("./hero-sections/vault-hero/demo"),
  },
  "vercel-hero": {
    demo: () => import("./hero-sections/vercel-hero/demo"),
  },
  "zoom-hero": {
    demo: () => import("./hero-sections/zoom-hero/demo"),
  },
  "cohort-navbar": {
    demo: () => import("./navbar-sections/cohort-navbar/demo"),
  },
  "curved-navbar": {
    demo: () => import("./navbar-sections/curved-navbar/demo"),
  },
  "hand-unicorn": {
    demo: () => import("./unicorn-section/hand-unicorn/demo"),
  },
  "ramp-unicorn": {
    demo: () => import("./unicorn-section/ramp-unicorn/demo"),
  },
  "rigel-unicorn": {
    demo: () => import("./unicorn-section/rigel-unicorn/demo"),
  },
  "void-unicorn": {
    demo: () => import("./unicorn-section/void-unicorn/demo"),
  },
}
