export const meta = {
  slug: "bevel-hero",
  title: "Bevel Hero",
  description:
    "Inspired by the bevel.health website design — a clean white editorial hero with a bold Georgia serif headline, eyebrow social-proof text, and an infinite auto-scrolling strip of portrait reel cards (Instagram-style). Each card shows a Cloudinary image with a user avatar, like/comment counts, and caption overlays. Left and right white gradient fades complete the marquee effect. Entrance animations powered by motion/react with staggered delays on eyebrow, headline, sub-copy, and the reel strip.",
  category: "hero-sections",
  preview: "/previews/hero-sections/bevel-hero/preview.mov",
  github: "vij-sameerb5",
  tags: [
    "hero",
    "light",
    "white",
    "scrolling",
    "marquee",
    "social",
    "cards",
    "reels",
    "animated",
    "serif",
    "editorial",
    "landing",
  ],
  dependencies: ["motion"],
  registryDependencies: [],
  version: 1,
  views: 0,
  likes: 0,
  installs: 0,
} as const
