// AUTO-GENERATED by scripts/build-registry.ts — do not edit manually.
// Run: npm run build:registry

export const codePaths: Record<string, string[]> = {
  "amero-hero": [
    "hero-sections/amero-hero/demo.tsx",
  ],
  "amind-hero": [
    "hero-sections/amind-hero/demo.tsx",
    "hero-sections/amind-hero/ui/Reviewband.tsx",
    "hero-sections/amind-hero/ui/header.tsx",
    "hero-sections/amind-hero/ui/hero.tsx",
    "hero-sections/amind-hero/ui/videosection.tsx",
  ],
  "brutal-hero": [
    "hero-sections/brutal-hero/demo.tsx",
    "hero-sections/brutal-hero/ui/navbar.tsx",
    "hero-sections/brutal-hero/ui/theme-toggle.tsx",
    "hero-sections/brutal-hero/ui/workflow-diagram.tsx",
  ],
  "caledera": [
    "hero-sections/caledera/demo.tsx",
  ],
  "crnacura-hero": [
    "hero-sections/crnacura-hero/demo.tsx",
    "hero-sections/crnacura-hero/splitting.d.ts",
  ],
  "dataanalytics-hero": [
    "hero-sections/dataanalytics-hero/demo.tsx",
  ],
  "drops-hero": [
    "hero-sections/drops-hero/demo.tsx",
    "hero-sections/drops-hero/ui/gsap-image-trail.tsx",
    "hero-sections/drops-hero/ui/index.ts",
  ],
  "glean-hero": [
    "hero-sections/glean-hero/demo.tsx",
  ],
  "glsl-hills-hero": [
    "hero-sections/glsl-hills-hero/demo.tsx",
    "hero-sections/glsl-hills-hero/ui/glsl-hills.tsx",
  ],
  "mainframe-hero": [
    "hero-sections/mainframe-hero/demo.tsx",
    "hero-sections/mainframe-hero/useTypewriter.ts",
  ],
  "new-hero": [
    "hero-sections/new-hero/demo.tsx",
    "hero-sections/new-hero/ui/badge.tsx",
    "hero-sections/new-hero/ui/button.tsx",
    "hero-sections/new-hero/ui/glow.tsx",
    "hero-sections/new-hero/ui/mockup.tsx",
  ],
  "posterscroll-hero": [
    "hero-sections/posterscroll-hero/demo.tsx",
    "hero-sections/posterscroll-hero/ui/peacock-logo.tsx",
    "hero-sections/posterscroll-hero/ui/tmdb-api-key.ts",
    "hero-sections/posterscroll-hero/ui/usePeacockScene.ts",
  ],
  "slider-hero": [
    "hero-sections/slider-hero/demo.tsx",
  ],
  "vault-hero": [
    "hero-sections/vault-hero/demo.tsx",
  ],
  "vercel-hero": [
    "hero-sections/vercel-hero/demo.tsx",
  ],
  "zoom-hero": [
    "hero-sections/zoom-hero/demo.tsx",
    "hero-sections/zoom-hero/ui/telescope-zoom.tsx",
  ],
  "cohort-navbar": [
    "navbar-sections/cohort-navbar/demo.tsx",
    "navbar-sections/cohort-navbar/ui/demo-shell.tsx",
    "navbar-sections/cohort-navbar/ui/text-scramble.tsx",
  ],
  "curved-navbar": [
    "navbar-sections/curved-navbar/demo.tsx",
  ],
  "supaste-navbar": [
    "navbar-sections/supaste-navbar/demo.tsx",
  ],
  "updated-navbar": [
    "navbar-sections/updated-navbar/demo.tsx",
  ],
  "blur-unicorn": [
    "unicorn-section/blur-unicorn/demo.tsx",
    "unicorn-section/blur-unicorn/ui/scene.json",
  ],
  "cat-unicorn": [
    "unicorn-section/cat-unicorn/demo.tsx",
    "unicorn-section/cat-unicorn/ui/scene.json",
  ],
  "cube-unicorn": [
    "unicorn-section/cube-unicorn/demo.tsx",
    "unicorn-section/cube-unicorn/ui/cube_scene.json",
  ],
  "earth-unicorn": [
    "unicorn-section/earth-unicorn/demo.tsx",
    "unicorn-section/earth-unicorn/ui/scene.json",
  ],
  "glass-unicorn": [
    "unicorn-section/glass-unicorn/demo.tsx",
    "unicorn-section/glass-unicorn/ui/scene.json",
  ],
  "hand-unicorn": [
    "unicorn-section/hand-unicorn/demo.tsx",
    "unicorn-section/hand-unicorn/ui/scene.json",
  ],
  "plane-unicorn": [
    "unicorn-section/plane-unicorn/demo.tsx",
    "unicorn-section/plane-unicorn/ui/scene.json",
  ],
  "ramp-unicorn": [
    "unicorn-section/ramp-unicorn/demo.tsx",
    "unicorn-section/ramp-unicorn/ui/scene.json",
  ],
  "rigel-unicorn": [
    "unicorn-section/rigel-unicorn/demo.tsx",
    "unicorn-section/rigel-unicorn/ui/scene.json",
  ],
  "ring-unicorn": [
    "unicorn-section/ring-unicorn/demo.tsx",
    "unicorn-section/ring-unicorn/ui/scene.json",
  ],
  "tree-unicorn": [
    "unicorn-section/tree-unicorn/demo.tsx",
    "unicorn-section/tree-unicorn/ui/scene.json",
  ],
  "void-unicorn": [
    "unicorn-section/void-unicorn/demo.tsx",
    "unicorn-section/void-unicorn/ui/scene.json",
  ],
  "walking-unicorn": [
    "unicorn-section/walking-unicorn/demo.tsx",
    "unicorn-section/walking-unicorn/ui/scene.json",
  ],
}
