// AUTO-GENERATED by scripts/build-registry.ts — do not edit manually.
// Run: npm run build:registry

export const codePaths: Record<string, string[]> = {
  "companion-grid": [
    "grid-sections/companion-grid/demo.tsx",
  ],
  "featured1-grid": [
    "grid-sections/featured1-grid/demo.tsx",
  ],
  "featured10-grid": [
    "grid-sections/featured10-grid/demo.tsx",
  ],
  "featured11-grid": [
    "grid-sections/featured11-grid/demo.tsx",
  ],
  "featured2-grid": [
    "grid-sections/featured2-grid/demo.tsx",
  ],
  "featured3-grid": [
    "grid-sections/featured3-grid/demo.tsx",
  ],
  "featured4-grid": [
    "grid-sections/featured4-grid/demo.tsx",
  ],
  "featured5-grid": [
    "grid-sections/featured5-grid/demo.tsx",
  ],
  "featured6-grid": [
    "grid-sections/featured6-grid/demo.tsx",
  ],
  "featured7-grid": [
    "grid-sections/featured7-grid/demo.tsx",
  ],
  "featured8-grid": [
    "grid-sections/featured8-grid/demo.tsx",
  ],
  "featured9-grid": [
    "grid-sections/featured9-grid/demo.tsx",
  ],
  "air-hero": [
    "hero-sections/air-hero/demo.tsx",
  ],
  "amero-hero": [
    "hero-sections/amero-hero/demo.tsx",
  ],
  "amind-hero": [
    "hero-sections/amind-hero/demo.tsx",
    "hero-sections/amind-hero/ui/Reviewband.tsx",
    "hero-sections/amind-hero/ui/header.tsx",
    "hero-sections/amind-hero/ui/hero.tsx",
    "hero-sections/amind-hero/ui/videosection.tsx",
  ],
  "bevel-hero": [
    "hero-sections/bevel-hero/demo.tsx",
  ],
  "bluish-hero": [
    "hero-sections/bluish-hero/demo.tsx",
  ],
  "brutal-hero": [
    "hero-sections/brutal-hero/demo.tsx",
    "hero-sections/brutal-hero/ui/navbar.tsx",
    "hero-sections/brutal-hero/ui/theme-toggle.tsx",
    "hero-sections/brutal-hero/ui/workflow-diagram.tsx",
  ],
  "caledera": [
    "hero-sections/caledera/demo.tsx",
  ],
  "card-hero": [
    "hero-sections/card-hero/demo.tsx",
  ],
  "crnacura-hero": [
    "hero-sections/crnacura-hero/demo.tsx",
    "hero-sections/crnacura-hero/splitting.d.ts",
  ],
  "dataanalytics-hero": [
    "hero-sections/dataanalytics-hero/demo.tsx",
  ],
  "drops-hero": [
    "hero-sections/drops-hero/demo.tsx",
    "hero-sections/drops-hero/ui/gsap-image-trail.tsx",
    "hero-sections/drops-hero/ui/index.ts",
  ],
  "figma-hero": [
    "hero-sections/figma-hero/demo.tsx",
  ],
  "glean-hero": [
    "hero-sections/glean-hero/demo.tsx",
  ],
  "glsl-hills-hero": [
    "hero-sections/glsl-hills-hero/demo.tsx",
    "hero-sections/glsl-hills-hero/ui/glsl-hills.tsx",
  ],
  "lena-hero": [
    "hero-sections/lena-hero/demo.tsx",
  ],
  "mainframe-hero": [
    "hero-sections/mainframe-hero/demo.tsx",
    "hero-sections/mainframe-hero/useTypewriter.ts",
  ],
  "new-hero": [
    "hero-sections/new-hero/demo.tsx",
    "hero-sections/new-hero/ui/badge.tsx",
    "hero-sections/new-hero/ui/button.tsx",
    "hero-sections/new-hero/ui/glow.tsx",
    "hero-sections/new-hero/ui/mockup.tsx",
  ],
  "osmos-hero": [
    "hero-sections/osmos-hero/demo.tsx",
  ],
  "oyo-hero": [
    "hero-sections/oyo-hero/demo.tsx",
  ],
  "paper-hero": [
    "hero-sections/paper-hero/demo.tsx",
    "hero-sections/paper-hero/ui/paper-card.tsx",
  ],
  "pop-hero": [
    "hero-sections/pop-hero/demo.tsx",
  ],
  "posterscroll-hero": [
    "hero-sections/posterscroll-hero/demo.tsx",
    "hero-sections/posterscroll-hero/ui/peacock-logo.tsx",
    "hero-sections/posterscroll-hero/ui/tmdb-api-key.ts",
    "hero-sections/posterscroll-hero/ui/usePeacockScene.ts",
  ],
  "scroll1-hero": [
    "hero-sections/scroll1-hero/demo.tsx",
  ],
  "scrolldown-hero": [
    "hero-sections/scrolldown-hero/demo.tsx",
  ],
  "selfie-hero": [
    "hero-sections/selfie-hero/demo.tsx",
  ],
  "slider-hero": [
    "hero-sections/slider-hero/demo.tsx",
  ],
  "synthesia-hero": [
    "hero-sections/synthesia-hero/demo.tsx",
  ],
  "vault-hero": [
    "hero-sections/vault-hero/demo.tsx",
  ],
  "vercel-hero": [
    "hero-sections/vercel-hero/demo.tsx",
  ],
  "video1-hero": [
    "hero-sections/video1-hero/demo.tsx",
  ],
  "wave-hero": [
    "hero-sections/wave-hero/demo.tsx",
  ],
  "zaveda-hero": [
    "hero-sections/zaveda-hero/demo.tsx",
  ],
  "zoom-hero": [
    "hero-sections/zoom-hero/demo.tsx",
    "hero-sections/zoom-hero/ui/telescope-zoom.tsx",
  ],
  "beam-zepa": [
    "interactive-illustrations/beam-zepa/demo.tsx",
    "interactive-illustrations/beam-zepa/ui/beam-zepa.tsx",
  ],
  "calendar-zepa": [
    "interactive-illustrations/calendar-zepa/demo.tsx",
    "interactive-illustrations/calendar-zepa/ui/calendar-zepa.tsx",
  ],
  "cards-zepa": [
    "interactive-illustrations/cards-zepa/demo.tsx",
    "interactive-illustrations/cards-zepa/ui/cards-zepa.tsx",
  ],
  "github-zepa": [
    "interactive-illustrations/github-zepa/demo.tsx",
    "interactive-illustrations/github-zepa/ui/github-zepa.tsx",
  ],
  "half-zepa": [
    "interactive-illustrations/half-zepa/demo.tsx",
    "interactive-illustrations/half-zepa/ui/half-zepa.tsx",
  ],
  "notification-zepa": [
    "interactive-illustrations/notification-zepa/demo.tsx",
    "interactive-illustrations/notification-zepa/ui/notification-zepa.tsx",
  ],
  "notify-zepa": [
    "interactive-illustrations/notify-zepa/demo.tsx",
    "interactive-illustrations/notify-zepa/ui/notify-zepa.tsx",
  ],
  "report-zepa": [
    "interactive-illustrations/report-zepa/demo.tsx",
    "interactive-illustrations/report-zepa/ui/report-zepa.tsx",
  ],
  "ring-zepa": [
    "interactive-illustrations/ring-zepa/demo.tsx",
    "interactive-illustrations/ring-zepa/ui/ring-zepa.tsx",
  ],
  "threat-zepa": [
    "interactive-illustrations/threat-zepa/demo.tsx",
    "interactive-illustrations/threat-zepa/ui/threat-zepa.tsx",
  ],
  "timeline-zepa": [
    "interactive-illustrations/timeline-zepa/demo.tsx",
    "interactive-illustrations/timeline-zepa/ui/timeline-zepa.tsx",
  ],
  "zepa-diagram": [
    "interactive-illustrations/zepa-diagram/demo.tsx",
    "interactive-illustrations/zepa-diagram/ui/zepa-diagram.tsx",
  ],
  "zepa-folder": [
    "interactive-illustrations/zepa-folder/demo.tsx",
    "interactive-illustrations/zepa-folder/ui/zepa-folder.tsx",
  ],
  "zoom-zepa": [
    "interactive-illustrations/zoom-zepa/demo.tsx",
    "interactive-illustrations/zoom-zepa/ui/zoom-zepa.tsx",
  ],
  "clipped-navbar": [
    "navbar-sections/clipped-navbar/demo.tsx",
  ],
  "cohort-navbar": [
    "navbar-sections/cohort-navbar/demo.tsx",
    "navbar-sections/cohort-navbar/ui/demo-shell.tsx",
    "navbar-sections/cohort-navbar/ui/text-scramble.tsx",
  ],
  "curved-navbar": [
    "navbar-sections/curved-navbar/demo.tsx",
  ],
  "photo-navbar": [
    "navbar-sections/photo-navbar/demo.tsx",
  ],
  "supaste-navbar": [
    "navbar-sections/supaste-navbar/demo.tsx",
  ],
  "updated-navbar": [
    "navbar-sections/updated-navbar/demo.tsx",
  ],
  "blur-unicorn": [
    "unicorn-section/blur-unicorn/demo.tsx",
    "unicorn-section/blur-unicorn/ui/scene.json",
  ],
  "cat-unicorn": [
    "unicorn-section/cat-unicorn/demo.tsx",
    "unicorn-section/cat-unicorn/ui/scene.json",
  ],
  "cube-unicorn": [
    "unicorn-section/cube-unicorn/demo.tsx",
    "unicorn-section/cube-unicorn/ui/cube_scene.json",
  ],
  "dove-unicorn": [
    "unicorn-section/dove-unicorn/demo.tsx",
    "unicorn-section/dove-unicorn/ui/scene.json",
  ],
  "earth-unicorn": [
    "unicorn-section/earth-unicorn/demo.tsx",
    "unicorn-section/earth-unicorn/ui/scene.json",
  ],
  "glass-unicorn": [
    "unicorn-section/glass-unicorn/demo.tsx",
    "unicorn-section/glass-unicorn/ui/scene.json",
  ],
  "hand-unicorn": [
    "unicorn-section/hand-unicorn/demo.tsx",
    "unicorn-section/hand-unicorn/ui/scene.json",
  ],
  "plane-unicorn": [
    "unicorn-section/plane-unicorn/demo.tsx",
    "unicorn-section/plane-unicorn/ui/scene.json",
  ],
  "ramp-unicorn": [
    "unicorn-section/ramp-unicorn/demo.tsx",
    "unicorn-section/ramp-unicorn/ui/scene.json",
  ],
  "reveal-unicorn": [
    "unicorn-section/reveal-unicorn/demo.tsx",
    "unicorn-section/reveal-unicorn/ui/scene.json",
  ],
  "rigel-unicorn": [
    "unicorn-section/rigel-unicorn/demo.tsx",
    "unicorn-section/rigel-unicorn/ui/scene.json",
  ],
  "ring-unicorn": [
    "unicorn-section/ring-unicorn/demo.tsx",
    "unicorn-section/ring-unicorn/ui/scene.json",
  ],
  "tree-unicorn": [
    "unicorn-section/tree-unicorn/demo.tsx",
    "unicorn-section/tree-unicorn/ui/scene.json",
  ],
  "void-unicorn": [
    "unicorn-section/void-unicorn/demo.tsx",
    "unicorn-section/void-unicorn/ui/scene.json",
  ],
  "walking-unicorn": [
    "unicorn-section/walking-unicorn/demo.tsx",
    "unicorn-section/walking-unicorn/ui/scene.json",
  ],
}
