import { existsSync } from "fs"
import { mkdir, readdir, readFile, writeFile } from "fs/promises"
import path from "path"
import { pathToFileURL } from "url"

const ROOT = process.cwd()
const REGISTRY_ROOT = path.join(ROOT, "content/registry")
const PUBLIC_R_DIR = path.join(ROOT, "public/r")

const SITE_URL =
  process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "") ??
  process.env.SITE_URL?.replace(/\/$/, "") ??
  "https://zepa.design"

const GENERATED_HEADER = `// AUTO-GENERATED by scripts/build-registry.ts — do not edit manually.
// Run: npm run build:registry
`

type RegistryMeta = {
  slug: string
  title: string
  description: string
  category: string
  preview: string
  github?: string
  tags: readonly string[]
  dependencies: readonly string[]
  registryDependencies: readonly string[]
  version: number | string
  views?: number
  likes?: number
  installs?: number
}

type ScannedComponent = {
  meta: RegistryMeta
  importPath: string
  importId: string
  dirRelative: string
  codeFiles: string[]
  registryFiles: Array<{ path: string; content: string; type: string }>
}

async function findMetaFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true })
  const files: string[] = []

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...(await findMetaFiles(fullPath)))
      continue
    }
    if (entry.isFile() && entry.name === "meta.ts") {
      files.push(fullPath)
    }
  }

  return files
}

function toImportId(dirRelative: string) {
  return dirRelative
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((part, index) =>
      index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)
    )
    .join("")
}

async function collectTsxFiles(
  componentDir: string,
  dirRelative: string
): Promise<string[]> {
  const files: string[] = []

  async function walk(current: string, prefix: string) {
    const entries = await readdir(current, { withFileTypes: true })

    for (const entry of entries) {
      const absolute = path.join(current, entry.name)
      const relative = prefix ? `${prefix}/${entry.name}` : entry.name

      if (entry.isDirectory()) {
        await walk(absolute, relative)
        continue
      }

      if (
        entry.isFile() &&
        entry.name !== "meta.ts" &&
        (entry.name.endsWith(".tsx") ||
          (entry.name.endsWith(".ts") && entry.name !== "meta.ts") ||
          entry.name.endsWith(".json"))
      ) {
        files.push(`${dirRelative}/${relative}`)
      }
    }
  }

  await walk(componentDir, "")
  return files.sort()
}

async function loadMeta(metaPath: string): Promise<ScannedComponent> {
  const componentDir = path.dirname(metaPath)
  const dirRelative = path
    .relative(REGISTRY_ROOT, componentDir)
    .split(path.sep)
    .join("/")

  const metaModule = await import(pathToFileURL(metaPath).href)
  const meta = metaModule.meta as RegistryMeta

  validateMeta(meta, dirRelative)

  const demoPath = path.join(componentDir, "demo.tsx")
  if (!existsSync(demoPath)) {
    throw new Error(`Missing demo.tsx for "${meta.slug}" at ${componentDir}`)
  }

  const codeFiles = await collectTsxFiles(componentDir, dirRelative)
  const registryFiles: ScannedComponent["registryFiles"] = []

  for (const file of codeFiles) {
    const absolute = path.join(REGISTRY_ROOT, file)
    const content = await readFile(absolute, "utf-8")
    const relativeInComponent = file.replace(`${dirRelative}/`, "")
    const type = relativeInComponent.startsWith("ui/")
      ? "registry:component"
      : "registry:example"

    registryFiles.push({
      path: relativeInComponent,
      content,
      type,
    })
  }

  return {
    meta,
    importPath: `./${dirRelative}/meta`,
    importId: toImportId(dirRelative),
    dirRelative,
    codeFiles,
    registryFiles,
  }
}

function validateMeta(meta: RegistryMeta, dirRelative: string) {
  const required: (keyof RegistryMeta)[] = [
    "slug",
    "title",
    "description",
    "category",
    "preview",
    "tags",
    "dependencies",
    "registryDependencies",
    "version",
  ]

  for (const key of required) {
    if (meta[key] === undefined || meta[key] === null) {
      throw new Error(`meta.ts missing "${key}" in ${dirRelative}`)
    }
  }

  const folderName = path.basename(dirRelative)
  if (meta.slug !== folderName) {
    throw new Error(
      `meta.slug "${meta.slug}" must match folder name "${folderName}" (${dirRelative})`
    )
  }
}

function generateItemsTs(components: ScannedComponent[]) {
  const imports = components
    .map((c) => `import { meta as ${c.importId} } from "${c.importPath}"`)
    .join("\n")

  const items = components.map((c) => `  ${c.importId},`).join("\n")

  return `${GENERATED_HEADER}
${imports}

export const registryItems = [
${items}
] as const

export type RegistryItem = (typeof registryItems)[number]
`
}

function generateLoadersTs(components: ScannedComponent[]) {
  const entries = components
    .map(
      (c) => `  "${c.meta.slug}": {
    demo: () => import("./${c.dirRelative}/demo"),
  },`
    )
    .join("\n")

  return `${GENERATED_HEADER}
import type { ComponentType } from "react"

type DemoModule = { default: ComponentType }

export const registryLoaders: Record<
  string,
  {
    demo: () => Promise<DemoModule>
  }
> = {
${entries}
}
`
}

function generateIndexTs() {
  return `${GENERATED_HEADER}
import { registryItems } from "./items"
import { registryLoaders } from "./loaders"

export const registry = registryItems.map((item) => ({
  ...item,
  demo: registryLoaders[item.slug].demo,
}))

export { registryItems } from "./items"
export { registryLoaders } from "./loaders"
`
}

function generateCodePathsTs(components: ScannedComponent[]) {
  const entries = components
    .map((c) => {
      const files = c.codeFiles.map((f) => `    "${f}",`).join("\n")
      return `  "${c.meta.slug}": [\n${files}\n  ],`
    })
    .join("\n")

  return `${GENERATED_HEADER}
export const codePaths: Record<string, string[]> = {
${entries}
}
`
}

function generateRegistryJson(components: ScannedComponent[]) {
  return {
    $schema: "https://ui.shadcn.com/schema/registry.json",
    name: "zepa",
    homepage: SITE_URL,
    items: components.map((c) => ({
      slug: c.meta.slug,
      title: c.meta.title,
      category: c.meta.category,
      description: c.meta.description,
      ...(c.meta.github ? { github: c.meta.github } : {}),
      tags: c.meta.tags,
      installUrl: `${SITE_URL}/r/${c.meta.slug}.json`,
    })),
  }
}

function generateShadcnRegistryJson(component: ScannedComponent) {
  return {
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: component.meta.slug,
    type: "registry:block",
    title: component.meta.title,
    description: component.meta.description,
    ...(component.meta.github ? { github: component.meta.github } : {}),
    dependencies: component.meta.dependencies,
    registryDependencies: component.meta.registryDependencies,
    files: component.registryFiles.map((file) => ({
      path: file.path,
      content: file.content,
      type: file.type,
      target: `components/${component.meta.slug}/${file.path}`,
    })),
  }
}

async function writeGeneratedFile(filePath: string, content: string) {
  await writeFile(filePath, content, "utf-8")
  console.log(`  ✓ ${path.relative(ROOT, filePath)}`)
}

async function main() {
  console.log("Building registry from meta.ts files...\n")

  const metaFiles = await findMetaFiles(REGISTRY_ROOT)

  if (metaFiles.length === 0) {
    throw new Error("No meta.ts files found under content/registry")
  }

  const components: ScannedComponent[] = []
  for (const metaPath of metaFiles.sort()) {
    components.push(await loadMeta(metaPath))
  }

  await mkdir(PUBLIC_R_DIR, { recursive: true })

  await writeGeneratedFile(
    path.join(REGISTRY_ROOT, "items.ts"),
    generateItemsTs(components)
  )
  await writeGeneratedFile(
    path.join(REGISTRY_ROOT, "loaders.ts"),
    generateLoadersTs(components)
  )
  await writeGeneratedFile(
    path.join(REGISTRY_ROOT, "index.ts"),
    generateIndexTs()
  )
  await writeGeneratedFile(
    path.join(ROOT, "lib/registry/code-paths.ts"),
    generateCodePathsTs(components)
  )
  await writeGeneratedFile(
    path.join(REGISTRY_ROOT, "registry.json"),
    `${JSON.stringify(generateRegistryJson(components), null, 2)}\n`
  )

  for (const component of components) {
    const shadcnJson = generateShadcnRegistryJson(component)
    await writeGeneratedFile(
      path.join(PUBLIC_R_DIR, `${component.meta.slug}.json`),
      `${JSON.stringify(shadcnJson, null, 2)}\n`
    )
  }

  console.log(`\nDone. Registered ${components.length} component(s).`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
