export const meta = {
  slug: "card-hero",
  title: "Card Hero",
  description:
    "Full-screen video hero with a centered glassmorphism pill navbar, large editorial headline, and a 3D tilt story card that follows the cursor via framer-motion springs. The card cycles two slides with progress bar animations, a person image with a sea-blue soft-light overlay, and frosted-glass action buttons.",
  category: "hero-sections",
  preview: "/previews/hero-sections/card-hero/preview.mov",
  github: "vij-sameerb5",
  tags: [
    "hero",
    "video",
    "card",
    "3d",
    "tilt",
    "glassmorphism",
    "dark",
    "animated",
    "framer-motion",
    "landing",
    "editorial",
    "navbar",
  ],
  dependencies: ["framer-motion"],
  registryDependencies: [],
  version: 1,
  views: 0,
  likes: 0,
  installs: 0,
} as const
