export const meta = {
  slug: "wave-hero",
  title: "Wave Hero",
  description:
    "Originally created by @franky-adl. An instanced 40×40 grid of tall cubes that ripple with expanding Gaussian wavefronts following the cursor. Built with Three.js — custom vertex shader injection, MouseTrail float texture, vignette + RGB-shift post-processing, and a GSAP staggered intro.",
  category: "hero-sections",
  preview: "/previews/hero-sections/wave-hero/preview.mov",
  github: "franky-adl",
  tags: [
    "hero",
    "3d",
    "threejs",
    "webgl",
    "shader",
    "wave",
    "grid",
    "cursor",
    "interactive",
    "dark",
    "gsap",
    "animated",
  ],
  dependencies: ["three", "gsap"],
  registryDependencies: [],
  version: 1,
  views: 0,
  likes: 0,
  installs: 0,
} as const
